# Generated by Django 5.0.1 on 2024-02-09 07:38

import news.custom_field
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_feed_alter_article_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name_plural': 'Articles'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Category'},
        ),
        migrations.AlterModelOptions(
            name='feed',
            options={'verbose_name_plural': 'Feeds'},
        ),
        migrations.AlterField(
            model_name='article',
            name='special',
            field=news.custom_field.CustomBooleanField(),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_homepage',
            field=news.custom_field.CustomBooleanField(),
        ),
    ]
