# Generated by Django 5.0.1 on 2024-02-12 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_alter_article_image_alter_article_name_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='article',
            constraint=models.UniqueConstraint(fields=('name', 'slug'), name='unique_name_slug_constraint'),
        ),
    ]
